# Generated by Django 5.2.7 on 2025-10-19 19:08

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("categories", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Form",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("unique_slug", models.SlugField(max_length=100, unique=True)),
                (
                    "visibility",
                    models.CharField(
                        choices=[("public", "Public"), ("private", "Private")],
                        default="public",
                        max_length=10,
                    ),
                ),
                (
                    "access_password",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("settings", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="forms",
                        to="categories.category",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="forms",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "form",
            },
        ),
        migrations.CreateModel(
            name="FormField",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "field_type",
                    models.CharField(
                        choices=[
                            ("text", "Text"),
                            ("number", "Number"),
                            ("email", "Email"),
                            ("select", "Select"),
                            ("checkbox", "Checkbox"),
                            ("radio", "Radio"),
                            ("textarea", "Textarea"),
                            ("date", "Date"),
                            ("file", "File"),
                        ],
                        max_length=20,
                    ),
                ),
                ("label", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("is_required", models.BooleanField(default=False)),
                (
                    "order_index",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                ("validation_rules", models.JSONField(blank=True, default=dict)),
                ("settings", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "form",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fields",
                        to="forms.form",
                    ),
                ),
            ],
            options={
                "db_table": "form_field",
            },
        ),
        migrations.CreateModel(
            name="FieldOption",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("label", models.CharField(max_length=255)),
                ("value", models.CharField(max_length=255)),
                (
                    "order_index",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "field",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="forms.formfield",
                    ),
                ),
            ],
            options={
                "db_table": "field_option",
            },
        ),
        migrations.AddIndex(
            model_name="form",
            index=models.Index(fields=["user"], name="form_user_id_aa4803_idx"),
        ),
        migrations.AddIndex(
            model_name="form",
            index=models.Index(fields=["unique_slug"], name="form_unique__0219a2_idx"),
        ),
        migrations.AddIndex(
            model_name="form",
            index=models.Index(fields=["category"], name="form_categor_152389_idx"),
        ),
        migrations.AddIndex(
            model_name="form",
            index=models.Index(
                fields=["visibility", "is_active"], name="form_visibil_b59e7a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="form",
            index=models.Index(fields=["created_at"], name="form_created_c1b2ee_idx"),
        ),
        migrations.AddIndex(
            model_name="formfield",
            index=models.Index(
                fields=["form", "order_index"], name="form_field_form_id_0deba6_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="formfield",
            unique_together={("form", "order_index")},
        ),
        migrations.AddIndex(
            model_name="fieldoption",
            index=models.Index(
                fields=["field", "order_index"], name="field_optio_field_i_3ad003_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="fieldoption",
            unique_together={("field", "order_index")},
        ),
    ]
