# Generated by Django 5.2.7 on 2025-10-19 19:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("forms", "0001_initial"),
        ("processes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FormView",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("session_id", models.CharField(db_index=True, max_length=255)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("viewed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "form",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="views",
                        to="forms.form",
                    ),
                ),
            ],
            options={
                "db_table": "form_view",
                "indexes": [
                    models.Index(
                        fields=["form", "viewed_at"],
                        name="form_view_form_id_b0a86c_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ProcessView",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("session_id", models.CharField(db_index=True, max_length=255)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("viewed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "process",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="views",
                        to="processes.process",
                    ),
                ),
            ],
            options={
                "db_table": "process_view",
                "indexes": [
                    models.Index(
                        fields=["process", "viewed_at"],
                        name="process_vie_process_627522_idx",
                    )
                ],
            },
        ),
    ]
