# Generated by Django 5.2.7 on 2025-10-19 19:08

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("categories", "0001_initial"),
        ("forms", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Process",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("unique_slug", models.SlugField(max_length=100, unique=True)),
                (
                    "visibility",
                    models.CharField(
                        choices=[("public", "Public"), ("private", "Private")],
                        default="public",
                        max_length=10,
                    ),
                ),
                (
                    "access_password",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                (
                    "process_type",
                    models.CharField(
                        choices=[("linear", "Linear"), ("free", "Free")],
                        default="linear",
                        max_length=10,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("settings", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="processes",
                        to="categories.category",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="processes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "processes",
                "db_table": "process",
            },
        ),
        migrations.CreateModel(
            name="ProcessStep",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "order_index",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                ("is_required", models.BooleanField(default=True)),
                ("conditions", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "form",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="process_steps",
                        to="forms.form",
                    ),
                ),
                (
                    "process",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="processes.process",
                    ),
                ),
            ],
            options={
                "db_table": "process_step",
            },
        ),
        migrations.AddIndex(
            model_name="process",
            index=models.Index(fields=["user"], name="process_user_id_e5b7aa_idx"),
        ),
        migrations.AddIndex(
            model_name="process",
            index=models.Index(
                fields=["unique_slug"], name="process_unique__76eee7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="process",
            index=models.Index(
                fields=["process_type"], name="process_process_5470b5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="processstep",
            index=models.Index(
                fields=["process", "order_index"], name="process_ste_process_4dc9bc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="processstep",
            index=models.Index(fields=["form"], name="process_ste_form_id_4ec7c3_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="processstep",
            unique_together={("process", "order_index")},
        ),
    ]
