# Generated by Django 5.2.7 on 2025-10-19 19:08

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("forms", "0001_initial"),
        ("processes", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProcessProgress",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("session_id", models.CharField(db_index=True, max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("abandoned", "Abandoned"),
                        ],
                        default="in_progress",
                        max_length=15,
                    ),
                ),
                (
                    "current_step_index",
                    models.PositiveIntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "completion_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("last_activity_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "process",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progress_records",
                        to="processes.process",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="process_progress",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "process_progress",
            },
        ),
        migrations.CreateModel(
            name="FormSubmission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("session_id", models.CharField(db_index=True, max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=10,
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "form",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="forms.form",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="form_submissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "process_progress",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="submissions",
                        to="submissions.processprogress",
                    ),
                ),
            ],
            options={
                "db_table": "form_submission",
            },
        ),
        migrations.CreateModel(
            name="ProcessStepCompletion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("skipped", "Skipped"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "progress",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="step_completions",
                        to="submissions.processprogress",
                    ),
                ),
                (
                    "step",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="completions",
                        to="processes.processstep",
                    ),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="step_completions",
                        to="submissions.formsubmission",
                    ),
                ),
            ],
            options={
                "db_table": "process_step_completion",
            },
        ),
        migrations.CreateModel(
            name="SubmissionAnswer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("text_value", models.TextField(blank=True, null=True)),
                (
                    "numeric_value",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=20, null=True
                    ),
                ),
                ("boolean_value", models.BooleanField(blank=True, null=True)),
                ("date_value", models.DateTimeField(blank=True, null=True)),
                ("array_value", models.JSONField(blank=True, null=True)),
                ("file_url", models.URLField(blank=True, max_length=500, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "field",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="forms.formfield",
                    ),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="submissions.formsubmission",
                    ),
                ),
            ],
            options={
                "db_table": "submission_answer",
            },
        ),
        migrations.AddIndex(
            model_name="processprogress",
            index=models.Index(
                fields=["process"], name="process_pro_process_f1d3b6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="processprogress",
            index=models.Index(fields=["user"], name="process_pro_user_id_39787f_idx"),
        ),
        migrations.AddIndex(
            model_name="processprogress",
            index=models.Index(
                fields=["session_id"], name="process_pro_session_23e0f6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="processprogress",
            index=models.Index(fields=["status"], name="process_pro_status_31cca0_idx"),
        ),
        migrations.AddIndex(
            model_name="processprogress",
            index=models.Index(
                fields=["last_activity_at"], name="process_pro_last_ac_64049e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="formsubmission",
            index=models.Index(fields=["form"], name="form_submis_form_id_ef3a8a_idx"),
        ),
        migrations.AddIndex(
            model_name="formsubmission",
            index=models.Index(fields=["user"], name="form_submis_user_id_ae55b3_idx"),
        ),
        migrations.AddIndex(
            model_name="formsubmission",
            index=models.Index(
                fields=["session_id"], name="form_submis_session_56376d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="formsubmission",
            index=models.Index(fields=["status"], name="form_submis_status_c299a9_idx"),
        ),
        migrations.AddIndex(
            model_name="formsubmission",
            index=models.Index(
                fields=["submitted_at"], name="form_submis_submitt_3b1a0f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="formsubmission",
            index=models.Index(
                fields=["process_progress"], name="form_submis_process_d91f3b_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="processstepcompletion",
            unique_together={("progress", "step")},
        ),
        migrations.AddIndex(
            model_name="submissionanswer",
            index=models.Index(
                fields=["submission"], name="submission__submiss_b40943_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="submissionanswer",
            index=models.Index(fields=["field"], name="submission__field_i_002905_idx"),
        ),
        migrations.AddIndex(
            model_name="submissionanswer",
            index=models.Index(
                fields=["field", "numeric_value"], name="submission__field_i_43dea3_idx"
            ),
        ),
    ]
