# Generated by Django 4.2.13 on 2025-10-31 17:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_beat', '0018_improve_crontab_helptext'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('report_type', models.CharField(choices=[('form_submissions', 'Form Submissions'), ('process_completions', 'Process Completions'), ('system_overview', 'System Overview')], max_length=50)),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=10)),
                ('filters', models.JSONField(blank=True, default=dict, help_text="e.g., {'form_ids': ['uuid1', 'uuid2']}")),
                ('send_to_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('output_format', models.CharField(choices=[('csv', 'CSV'), ('json', 'JSON')], default='csv', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('periodic_task', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='django_celery_beat.periodictask')),
                ('send_to_webhook', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='notifications.webhook')),
                ('target', models.ForeignKey(help_text='Admin user who owns this schedule', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'report_schedule',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=15)),
                ('report_type', models.CharField(max_length=50)),
                ('file_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('file_size', models.BigIntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('schedule', models.ForeignKey(blank=True, help_text='Scheduled job that triggered this (if any)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='notifications.reportschedule')),
                ('triggered_by', models.ForeignKey(blank=True, help_text='User who manually triggered this (if any)', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'report_instance',
                'ordering': ['-created_at'],
            },
        ),
    ]
